# CONFIGURAÇÃO DE CORS DINÂMICA
app.frontend.url=${FRONTEND_URL:http://localhost:4200}

# BANCO DE DADOS DINÂMICO
# Se a variável SPRING_DATASOURCE_URL não for injetada pelo Render (na nuvem), 
# o Spring usará diretamente a sua URL do Neon configurada após os dois-pontos (:).
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-quiet-morning-ateec3a5.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_wW20RkdIEYrV}

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true