# Nome da sua aplicação
spring.application.name=rfx-estudos



# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'none' porque já criamos as tabelas manualmente via script SQL na Neon
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
