# Nome da sua aplicação
spring.application.name=rfx-estudos

# URL de Conexão do PostgreSQL (Substitua pelos dados fornecidos pela Neon)
spring.datasource.url=jdbc:postgresql://ep-quiet-morning-ateec3a5.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_wW20RkdIEYrV

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'none' porque já criamos as tabelas manualmente via script SQL na Neon
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true